---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slate-deployment
  labels:
    app: slate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slate
  template:
    metadata:
      labels:
        app: slate
    spec:
      containers:
        - name: slate
          image: us.gcr.io/##project##/miris/slate:latest
          volumeMounts:
          - name: secrets
            mountPath: "/data"
            readOnly: true
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1

      volumes:
      - name: secrets
        secret:
          secretName: miris-slate-secret
---
apiVersion: v1
kind: Service
metadata:
  name: slate-service
  namespace: default
  labels:
    app: slate
spec:
  type: NodePort
  selector:
    app: slate
  ports:
    - port: 80
      name: http
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: slate-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  rules:
  - host: slate.miris.io
    http:
      paths:
      - backend:
          serviceName: slate-service
          servicePort: 80
  tls:
    - hosts:
        - 'slate.miris.io'
      secretName: slate-miris-tls
